### ISSUE TITLE
Backend: Status 2 & 3 result in no response / indefinite waittime

### ISSUE THREAD

**Issue by kormad16** [TheProgrammer21/WorkshopOrganisation#23]
Expected behavior: Return a ObligatoryUnit response Object

**Comment by TheProgrammer21** [comment]
Cannot be reproduced for GET /getAllObligatoryUnits. Specify the API endpoint if this was the wrong.

**Comment by TheProgrammer21** [comment]
Issue is relating to GET /obilgatoryunit/{id} with the status of the obligatory unit set to 2 or 3.

**Comment by TheProgrammer21** [comment]
Bug fixed
